CREATE OR REPLACE FUNCTION MEMBROS_INCLUI_PROJETO() RETURNS TRIGGER AS $membrosadd$
BEGIN
	INSERT INTO MEMBROS(USUARIO_EMAIL,PROJETO_ID) VALUES(NEW.usuario_criador, NEW.ID);
	return new;
END;
$membrosadd$
LANGUAGE 'plpgsql'; 



CREATE TRIGGER membrosadd AFTER  INSERT ON PROJETO
    FOR EACH ROW EXECUTE PROCEDURE MEMBROS_INCLUI_PROJETO();


